# Generated by Django 2.2 on 2019-04-09 06:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_auto_20190409_0613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='members',
            field=models.ManyToManyField(blank=True, null=True, related_name='rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='room',
            name='moderators',
            field=models.ManyToManyField(blank=True, null=True, related_name='moderated_rooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
